### ISSUE TITLE
apps/partytown/lib 404

### ISSUE THREAD

**Issue by i7eo** [j0Shi82/shopify-partydawn#1]
TypeError: Failed to register a ServiceWorker for scope ('https://bugx28rsf1h2mfn5-26358844.shopifypreview.com/apps/partytown/lib/debug/') with script ('https://bugx28rsf1h2mfn5-26358844.shopifypreview.com/apps/partytown/lib/debug/partytown-sw.js'): A bad HTTP response code (404) was received when fetching the script.

you can see https://bugx28rsf1h2mfn5-26358844.shopifypreview.com/?pb=0

**Comment by i7eo** [comment]
Use https://github.com/edlaver/cloudflare-worker-partytown-shopify-app-proxy to solve it.

**Comment by j0Shi82** [comment]
Yes you need to reverse proxy the Partytown library. Seems like you figured it out, but I'll check to update the docs in case it's not clear. Coudflare Workers have 100k free requests which should cover all test cases.
